### ISSUE TITLE
"DBSQL isn't available in this workspace" and "API Call Error"  even though the user has permission to create SQL DW

### ISSUE THREAD

**Issue by Jaipats** [databricks-demos/dbdemos#85]
Issue 1: User is getting a warning "DBSQL isn't available in this workspace. Only Premium/Enterprise workspaces are supported", even though the workspaces is in Enterprise tier and the user has access to create SQL DW.
Issue 2: API Call Error. Please see attached screenshot.
![image-3](https://github.com/databricks-demos/dbdemos/assets/107501051/f5946f22-bd61-4e2c-a29b-9d1548dbed29)

**Comment by QuentinAmbard** [comment]
Hi @Jaipats , I believe we fixed this issue in the latest version, sorry it's been a busy month, could you let us know if it's still the case? It should show a nice warning

**Comment by Jaipats** [comment]
Hi @QuentinAmbard , yes the message appears and the customer had an issue with their network which was throwing other errors. It is not fixed. Thanks for your help!

**Comment by ukrcvss** [comment]
i was facing the similar issue with the databricks notebook.  it was due to the route table attached to the subnet of the databricks . once i disabled the route able installation works fine

**Comment by abhinabanaskar** [comment]
Can you please elaborate in detail in terms of how to disable the route table attached to the subnet of the databricks installation
